repos:
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.9.1
  hooks:
   - id: nbqa-black
     args: ["--skip-string-normalization", "--line-length=100"]
     additional_dependencies: [black==23.3.0]
   - id: nbqa-pyupgrade
     args: ["--py38-plus"]
   - id: nbqa-isort
     args: ["--profile=black"]