name: Pylint and nbQA

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install pylint nbqa black==23.3.0 isort pyupgrade

      - name: Analyze the code with pylint
        run: |
          pylint --rcfile=.pylintrc $(git ls-files '*.py')

      - name: Run nbQA on notebooks
        run: |
          nbqa black . --skip-string-normalization --line-length=100
          nbqa pyupgrade . --py38-plus
          nbqa isort . --profile=black
